### ISSUE TITLE
instead of running a discord server around a cheat that isnt yours

### ISSUE THREAD

**Issue by AmpujaKid** [AnonHexo/Krunker#3]
just join the gaming gurus discord

https://discord.gg/4GtMPruhft

**Comment by AnonHexo** [comment]
bro just read the readme, i clearly say its not mine and also, don't cheat, hacking is for noobs learn to play the game bruh
as you can see I removed all the krunker hack links so...

**Comment by AmpujaKid** [comment]
> bro just read the readme, i clearly say its not mine and also, don't cheat, hacking is for noobs learn to play the game bruh
> as you can see I removed all the krunker hack links so...

https://discord.gg/4GtMPruhft
https://discord.gg/4GtMPruhft
https://discord.gg/4GtMPruhft
https://discord.gg/4GtMPruhft
https://discord.gg/4GtMPruhft
https://discord.gg/4GtMPruhft
https://discord.gg/4GtMPruhft
https://discord.gg/4GtMPruhft
https://discord.gg/4GtMPruhft
https://discord.gg/4GtMPruhft
https://discord.gg/4GtMPruhft
